import Link from 'next/link'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

const pages = [
  { id: 1, text: 'Home', link: '/' },
  { id: 2, text: 'About', link: '/about' },
  { id: 3, text: 'Posts', link: '/posts' }
]

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <head>
        <title>Blog Prisma</title>
        <link rel='stylesheet' href='https://unpkg.com/simpledotcss/simple.min.css' />
      </head>
      <body>
        <nav>
          {pages.map((page) => {
            return (<Link key={page.id} href={page.link}>{page.text}</Link>)
          })}
        </nav>
        {children}
      </body>
    </html>
  )
}
